services: 
  backend:
    container_name: "queue_bot"
    env_file: 
      - path: ./.env
        required: true
    tty: true
    build: 
      context: .
      target: main
      dockerfile: Dockerfile
    environment:
      - OAUTH2_TOKEN_FILE=/run/secrets/token
      - OAUTH2_CREDENTIALS_FILE=/run/secrets/credentials
      - SQLITE_FILE=../data/sqlite3.db
      - SQLITE_INIT_FILE=../sql/db_setup.sql
      - DATA_DIRECTORY=../data
    volumes:
      - ./data:/app/data
      - ./sql:/app/sql
    secrets:
      - credentials
      - token
secrets:
  credentials:
   file: ./src/credentials.json
  token:
   file: ./src/token.json