services: 
  backend:
    container_name: "queue_bot"
    env_file: 
      - path: .env
        required: true
    tty: true
    build: 
      context: .
      target: main
    volumes:
      - ./data:/app/data
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json:ro