package constants

type State string
func (st State) String() string {
	return string(st) + " state"
}

const (
	IDLE_STATE State = "idle"
)

const (
	ADMIN_SUBMIT_STATES State = "submit"

	ADMIN_SUBMIT_START_STATE State    = ADMIN_SUBMIT_STATES + "_start"
	ADMIN_SUBMITTING_NAME_STATE  State = ADMIN_SUBMIT_STATES + "_name"
	ADMIN_SUBMITTING_GROUP_STATE State = ADMIN_SUBMIT_STATES + "_group"
	ADMIN_SUBMITTING_PROOF_STATE State = ADMIN_SUBMIT_STATES + "_proof"
	ADMIN_WAITING_STATE          State = ADMIN_SUBMIT_STATES + "_waiting"
)

const (
	GROUP_STATES State = "group"

	GROUP_SUBMIT_START_STATE    State = GROUP_STATES + "_submit"
	GROUP_SUBMIT_GROUPNAME_STATE State = GROUP_STATES + "_groupname"
	GROUP_SUBMIT_NAME_STATE      State = GROUP_STATES + "_name"
	GROUP_WAITING_STATE          State = GROUP_STATES + "_waiting"
)

const (
	LABWORK_SUBMIT_STATES State = "seq_lab"

	LABWORK_SUBMIT_START_STATE State  = LABWORK_SUBMIT_STATES + "_submit"
	LABWORK_SUBMIT_WAITING_STATE State = LABWORK_SUBMIT_STATES + "_wait"
	LABWORK_SUBMIT_NUMBER_STATE  State= LABWORK_SUBMIT_STATES + "_num"
	LABWORK_SUBMIT_PROOF_STATE   State= LABWORK_SUBMIT_STATES + "_proof_submit"
)

const (
	LABWORK_ADD_STATES State = "custom_lab"

	LABWORK_ADD_START_STATE      State = LABWORK_ADD_STATES + "_start"
	LABWORK_ADD_SUBMIT_NAME_STATE State= LABWORK_ADD_STATES + "_name"
	LABWORK_ADD_WAITING_STATE     State = LABWORK_ADD_STATES + "_wait"
)

const (
	QUEUE_STATES State = "queue"

	QUEUE_START_STATE   State = QUEUE_STATES + "_start"
	QUEUE_WAITING_STATE State = QUEUE_STATES + "_wait"
)

const ADMIN_STATES State = "admin"
const (
	DELETE_STATES State = ADMIN_STATES + "_del"

	DELETE_START_STATE  State = DELETE_STATES + "_start"
	DELETE_CHOOSE_STATE  State = DELETE_STATES + "_choose"
	DELETE_WAITING_STATE State = DELETE_STATES + "_wait"
)

const (
	DELETE_REQUEST_STATES State= ADMIN_STATES + "_del_req"

	DELETE_REQUEST_START      State  = DELETE_REQUEST_STATES + "_start"
	DELETE_REQUEST_WAITING      State = DELETE_REQUEST_STATES + "_wait"
	DELETE_REQUEST_CHOOSE_STATE State = DELETE_REQUEST_STATES + "_choose"
)

const (
	REORDER_REQUESTS_STATES State = ADMIN_STATES + "_reord_req"
	REORDER_REQUEST_START_STATE State = REORDER_REQUESTS_STATES + "_start"
	REORDER_WAITING_STATE State  = REORDER_REQUESTS_STATES + "_waiting"
	REORDER_CHOOSE_STATE State = REORDER_REQUESTS_STATES + "_choose"

	REORDER_REQUEST_METHOD_STATE State = REORDER_REQUESTS_STATES + "_meth"
	REORDER_REQUEST_ORDER_STATE State= REORDER_REQUESTS_STATES + "_ord"
	REORDER_CHOOSE_LESSON_STATE State = REORDER_REQUESTS_STATES + "chs_lsn"
)

