package constants

const (
	IDLE_STATE = "idle"
)

const (
	ADMIN_SUBMIT_STATES = "submit"

	ADMIN_SUBMIT_START_STATE     = ADMIN_SUBMIT_STATES + "_start"
	ADMIN_SUBMITTING_NAME_STATE  = ADMIN_SUBMIT_STATES + "_name"
	ADMIN_SUBMITTING_GROUP_STATE = ADMIN_SUBMIT_STATES + "_group"
	ADMIN_SUBMITTING_PROOF_STATE = ADMIN_SUBMIT_STATES + "_proof"
	ADMIN_WAITING_STATE          = ADMIN_SUBMIT_STATES + "_waiting"
)

const (
	GROUP_STATES = "group"

	GROUP_SUBMIT_START_STATE     = GROUP_STATES + "_submit"
	GROUP_SUBMIT_GROUPNAME_STATE = GROUP_STATES + "_groupname"
	GROUP_SUBMIT_NAME_STATE      = GROUP_STATES + "_name"
	GROUP_WAITING_STATE          = GROUP_STATES + "_waiting"
)

const (
	LABWORK_SUBMIT_STATES = "seq_lab"

	LABWORK_SUBMIT_START_STATE   = LABWORK_SUBMIT_STATES + "_submit"
	LABWORK_SUBMIT_WAITING_STATE = LABWORK_SUBMIT_STATES + "_wait"
	LABWORK_SUBMIT_NUMBER_STATE  = LABWORK_SUBMIT_STATES + "_num"
	LABWORK_SUBMIT_PROOF_STATE   = LABWORK_SUBMIT_STATES + "_proof_submit"
)

const (
	LABWORK_ADD_STATES = "custom_lab"

	LABWORK_ADD_START_STATE       = LABWORK_ADD_STATES + "_start"
	LABWORK_ADD_SUBMIT_NAME_STATE = LABWORK_ADD_STATES + "_name"
	LABWORK_ADD_WAITING_STATE     = LABWORK_ADD_STATES + "_wait"
)

const (
	QUEUE_STATES = "queue"

	QUEUE_START_STATE   = QUEUE_STATES + "_start"
	QUEUE_WAITING_STATE = QUEUE_STATES + "_wait"
)

const ADMIN_STATES = "admin"
const (
	DELETE_STATES = ADMIN_STATES + "_del"

	DELETE_START_STATE   = DELETE_STATES + "_start"
	DELETE_CHOOSE_STATE  = DELETE_STATES + "_choose"
	DELETE_WAITING_STATE = DELETE_STATES + "_wait"
)

const (
	DELETE_REQUEST_STATES = ADMIN_STATES + "_del_req"

	DELETE_REQUEST_START        = DELETE_REQUEST_STATES + "_start"
	DELETE_REQUEST_WAITING      = DELETE_REQUEST_STATES + "_wait"
	DELETE_REQUEST_CHOOSE_STATE = DELETE_REQUEST_STATES + "_choose"
)
