package constants

const (
	IGNORE_CALLBACKS = "ignore"
)

const (
	GROUP_CALLBACKS = "group"
)

const (
	ADMIN_CALLBACKS = "admin"
)

const (
	LABWORK_CALLBACKS               = "lab"
	LABWORK_DISCIPLINE_CALLBACKS    = LABWORK_CALLBACKS + "_discipline"
	LABWORK_TIME_CALLBACKS          = LABWORK_CALLBACKS + "_time"
	LABWORK_CONSIDERATION_CALLBACKS = LABWORK_CALLBACKS + "_consideration"
)

const (
	CALENDAR_CALLBACKS               = "calendar"
	CALENDAR_DATE_CALLBACKS          = CALENDAR_CALLBACKS + "_date"
	CALENDAR_NAVIGATE_BACK_CALLBACK  = CALENDAR_CALLBACKS + "_back"
	CALENDAR_NAVIGATE_FRONT_CALLBACK = CALENDAR_CALLBACKS + "_front"
)

const (
	TIME_PICKER_CALLBACKS            = "time"
	TIME_MINUTES_INCREASE_CALLBACKS  = TIME_PICKER_CALLBACKS + "_m_incr"
	TIME_MINUTES_DESCREASE_CALLBACKS = TIME_PICKER_CALLBACKS + "_m_decr"
	TIME_HOURS_INCREASE_CALLBACKS    = TIME_PICKER_CALLBACKS + "_h_incr"
	TIME_HOURS_DECREASE_CALLBACKS    = TIME_PICKER_CALLBACKS + "h_decr"
	TIME_SUBMIT                      = TIME_PICKER_CALLBACKS + "_submit"
	TIME_CANCEL                      = TIME_PICKER_CALLBACKS + "_cancel"
)
