FROM golang:alpine AS main

WORKDIR /app

ARG UID=1000
ARG GID=1000
ENV UID=${UID}
ENV GID=${GID}

RUN --mount=type=secret,id=credentials.json
RUN --mount=type=secret,id=token.json

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install golang.org/x/tools/gopls@latest

RUN apk add --no-cache --update gcc

COPY go.mod .
COPY go.sum .

ENTRYPOINT ["/bin/sh"]
