FROM golang:bookworm AS main

WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates

ARG UID=1000
ARG GID=1000
ENV UID=${UID}
ENV GID=${GID}

COPY ./go.mod .
COPY ./go.sum .

RUN --mount=type=secret,id=credentials.json
RUN --mount=type=secret,id=token.json

ENTRYPOINT ["/bin/bash"]
