services: 
  backend: 
    container_name: "queue_bot_dev"
    stdin_open: true
    tty: true
    build: 
      context: .
      dockerfile: ./.devcontainer/Dockerfile.dev
      target: main
    volumes:
      - ./src:/app/src
      - ./.vscode:/app/.vscode
      - ./.devcontainer:/app/.devcontainer
      