services: 
  backend_dev: 
    container_name: "queue_bot_dev"
    env_file: 
      - path: ../src/.env
        required: true
    stdin_open: true
    tty: true
    build: 
      context: ..
      dockerfile: ./.devcontainer/Dockerfile.dev
      target: main
    environment:
      - OAUTH2_TOKEN_FILE=/run/secrets/token.json
      - OAUTH2_CREDENTIALS_FILE=/run/secrets/credentials.json
      - SQLITE_FILE=../data/sqlite3.db
      - SQLITE_INIT_FILE=../sql/db_setup.sql
    volumes:
      - ../.vscode:/app/.vscode
      - ../:/app
    secrets:
      - credentials
      - token
secrets:
  credentials:
   file: ../src/credentials.json
  token:
   file: ../src/token.json