services: 
  backend_dev: 
    container_name: "queue_bot_dev"
    env_file: 
      - path: ../src/.env
        required: true
    stdin_open: true
    tty: true
    build: 
      context: ..
      dockerfile: ./.devcontainer/Dockerfile.dev
      target: main
    develop:
     watch:
      - action: sync
        path: ./src
        target: /app/src
        ignore:
          - bin/
      - action: rebuild
        path: go.mod
    environment:
      - OAUTH2_TOKEN_FILE=/run/secrets/token.json
      - OAUTH2_CREDENTIALS_FILE=/run/secrets/credentials.json
      - SQLITE_FILE=../data/sqlite3.db
      - SQLITE_INIT_FILE=../sql/db_setup.sql
    ports:
      - "4000:4000"  
    volumes:
      - ../src:/app/src
      - ../data:/app/data
      - ../sql:/app/sql
      - ../.vscode:/app/.vscode
      - ../.devcontainer:/app/.devcontainer
    secrets:
      - credentials
      - token
secrets:
  credentials:
   file: ../src/credentials.json
  token:
   file: ../src/token.json